#!/bin/sh
# ============================================================================
# Log rotation installer (logrotate) — agent_chatroom
# ----------------------------------------------------------------------------
# Background: when started by systemd, this service's stdout/stderr are
#   appended to  gin_log/agent_chatroom.log  and  gin_log/agent_chatroom-error.log
#   (see the unit: StandardOutput/StandardError=append:...). Those files are
#   never rotated by themselves and may grow to hundreds of MB, so this script
#   installs a daily rotation that keeps the most recent 5 archives.
#
# Installs /etc/logrotate.d/<service> with:
#   daily / rotate 5 / dateext / compress / delaycompress / copytruncate /
#   missingok / notifempty        (+ optional "su <user> <group>")
#   copytruncate: copy then truncate — the running process keeps its file
#   handle, no restart needed.
#
# Usage (root, once):
#   sudo sh install_logrotate.sh
#
# Verify / rotate now / prerequisites:
#   logrotate -d /etc/logrotate.d/agent_chatroom      # dry run (no rotation)
#   sudo logrotate -f /etc/logrotate.d/agent_chatroom # rotate immediately
#   # logrotate must be scheduled by the system (cron.daily or logrotate.timer)
#
# If the existing log is already very large, truncate it once *before* rotating
# so the first rotation does not copy hundreds of MB:
#   sudo sh -c ': > <deploy dir>/gin_log/agent_chatroom.log'
#
# Environment overrides: SERVICE, LOGROTATE_USER, LOGROTATE_GROUP
# ============================================================================
set -eu

# Script directory = project root (gin_log/ lives next to it)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

SERVICE="${SERVICE:-agent_chatroom}"
DEST="/etc/logrotate.d/${SERVICE}"
LOG_DIR="${LOG_DIR:-$SCRIPT_DIR/gin_log}"

if [ "$(id -u)" -ne 0 ]; then
  echo "[logrotate] root required (needs to write ${DEST}): sudo sh $0" >&2
  exit 1
fi

if [ -e "$DEST" ]; then
  echo "[logrotate] ${DEST} already exists - refusing to overwrite (remove it first to regenerate)" >&2
  exit 1
fi

if ! command -v logrotate >/dev/null 2>&1; then
  echo "[logrotate] logrotate not found. Install it first:" >&2
  echo "  yum install -y logrotate   |   apt-get install -y logrotate" >&2
  exit 1
fi

# Which files to rotate: read them from the unit (StandardOutput/StandardError)
# so the config follows the unit if paths change; fall back to the defaults.
LOG_FILES_RAW=""
LOG_FILES=""
for prop in StandardOutput StandardError; do
  val="$(systemctl show -p "$prop" --value "$SERVICE" 2>/dev/null || true)"
  case "$val" in
    append:*|file:*) LOG_FILES_RAW="$LOG_FILES_RAW ${val#*:}" ;;
  esac
done
if [ -z "$LOG_FILES_RAW" ]; then
  LOG_FILES_RAW=" ${LOG_DIR}/agent_chatroom.log ${LOG_DIR}/agent_chatroom-error.log"
fi
# 生成配置时给每个路径加引号（路径含空格也安全）
for f in $LOG_FILES_RAW; do
  LOG_FILES="$LOG_FILES \"$f\""
done

# Which user should perform the rotation? Two constraints decide it:
#   1) copytruncate rewrites the log files -> that user must be able to write them;
#   2) logrotate refuses when the parent directory is group/other-writable, and
#      `su` to a safe user is the documented way around that.
# With `StandardOutput=append:` systemd creates the files as **root**, so the
# OWNER OF THE LOG FILE wins: a rotation running as a non-root user simply
# cannot truncate a root-owned file (it fails with a permission error), while
# rotating as root is always allowed.
# Resolution order: LOGROTATE_USER override -> log file owner -> unit User=.
LOG_PROBE=""
for f in $LOG_FILES_RAW; do
  if [ -e "$f" ]; then LOG_PROBE="$f"; break; fi
done
FILE_OWNER=""
FILE_GROUP=""
if [ -n "$LOG_PROBE" ]; then
  FILE_OWNER="$(stat -c '%U' "$LOG_PROBE" 2>/dev/null || true)"
  FILE_GROUP="$(stat -c '%G' "$LOG_PROBE" 2>/dev/null || true)"
fi
LOGROTATE_USER="${LOGROTATE_USER:-${FILE_OWNER:-$(systemctl show -p User --value "$SERVICE" 2>/dev/null || true)}}"
LOGROTATE_GROUP="${LOGROTATE_GROUP:-${FILE_GROUP:-$(systemctl show -p Group --value "$SERVICE" 2>/dev/null || true)}}"
SU_LINE=""
if [ -n "$LOGROTATE_USER" ]; then
  SU_LINE="    su ${LOGROTATE_USER} ${LOGROTATE_GROUP:-$LOGROTATE_USER}"
fi

{
  echo "# ${SERVICE} daily log rotation (generated by $(basename "$0")), keep 5 archives"
  printf '%s {\n' "$LOG_FILES"
  echo "    daily"
  echo "    rotate 5"
  echo "    dateext"
  echo "    compress"
  echo "    delaycompress"
  echo "    copytruncate"
  echo "    missingok"
  echo "    notifempty"
  [ -n "$SU_LINE" ] && echo "$SU_LINE"
  echo "}"
} > "$DEST"

echo "[logrotate] wrote ${DEST}"
echo "  log files :${LOG_FILES}"
echo "  rule      : daily, keep last 5, compress archives"
if [ -n "$SU_LINE" ]; then
  echo "  as user   : ${LOGROTATE_USER}:${LOGROTATE_GROUP:-$LOGROTATE_USER} (owner of the log files)"
else
  echo "  as user   : (not set - logrotate runs as root)"
fi
echo "  note      : keep this user able to write the log files, otherwise"
echo "              copytruncate fails (systemd append: files are usually root-owned)"
echo
echo "Dry run (no rotation):    logrotate -d ${DEST}"
echo "Rotate now:               logrotate -f ${DEST}"
echo "Daily job enabled?        ls -l /etc/cron.daily/logrotate  |  systemctl list-timers | grep logrotate"
