#!/bin/sh
# ============================================================================
# Log rotation installer (logrotate) — agent_chatroom
# ----------------------------------------------------------------------------
# Background: when started by systemd, this service's stdout/stderr are
#   appended to  gin_log/agent_chatroom.log  and  gin_log/agent_chatroom-error.log
#   (see the unit: StandardOutput/StandardError=append:...). Those files are
#   never rotated by themselves and may grow to hundreds of MB, so this script
#   installs a daily rotation that keeps the most recent 5 archives.
#
# Installs /etc/logrotate.d/<service> with:
#   daily / rotate 5 / dateext / compress / delaycompress / copytruncate /
#   missingok / notifempty        (+ optional "su <user> <group>")
#   copytruncate: copy then truncate — the running process keeps its file
#   handle, no restart needed.
#
# Usage (root, once):
#   sudo sh install_logrotate.sh
#
# Verify / rotate now / prerequisites:
#   logrotate -d /etc/logrotate.d/agent_chatroom      # dry run (no rotation)
#   sudo logrotate -f /etc/logrotate.d/agent_chatroom # rotate immediately
#   # logrotate must be scheduled by the system (cron.daily or logrotate.timer)
#
# If the existing log is already very large, truncate it once *before* rotating
# so the first rotation does not copy hundreds of MB:
#   sudo sh -c ': > <deploy dir>/gin_log/agent_chatroom.log'
#
# Environment overrides: SERVICE, LOGROTATE_USER, LOGROTATE_GROUP
# ============================================================================
set -eu

# Script directory = project root (gin_log/ lives next to it)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

SERVICE="${SERVICE:-agent_chatroom}"
DEST="/etc/logrotate.d/${SERVICE}"
LOG_DIR="${LOG_DIR:-$SCRIPT_DIR/gin_log}"

if [ "$(id -u)" -ne 0 ]; then
  echo "[logrotate] root required (needs to write ${DEST}): sudo sh $0" >&2
  exit 1
fi

if [ -e "$DEST" ]; then
  echo "[logrotate] ${DEST} already exists - refusing to overwrite (remove it first to regenerate)" >&2
  exit 1
fi

if ! command -v logrotate >/dev/null 2>&1; then
  echo "[logrotate] logrotate not found. Install it first:" >&2
  echo "  yum install -y logrotate   |   apt-get install -y logrotate" >&2
  exit 1
fi

# Which files to rotate: read them from the unit (StandardOutput/StandardError)
# so the config follows the unit if paths change; fall back to the defaults.
LOG_FILES=""
for prop in StandardOutput StandardError; do
  val="$(systemctl show -p "$prop" --value "$SERVICE" 2>/dev/null || true)"
  case "$val" in
    append:*|file:*) LOG_FILES="$LOG_FILES \"${val#*:}\"" ;;   # 引号包住，路径含空格也安全
  esac
done
if [ -z "$LOG_FILES" ]; then
  LOG_FILES=" \"${LOG_DIR}/agent_chatroom.log\" \"${LOG_DIR}/agent_chatroom-error.log\""
fi

# Rotate as the service user: when the log directory is owned by a non-root user,
# running logrotate as root reports "parent directory has insecure permissions";
# `su <user> <group>` avoids that. Resolved from the unit's User=/Group=
# (LOGROTATE_USER / LOGROTATE_GROUP override). If it cannot be resolved, or the
# service runs as root, the `su` line is omitted.
LOGROTATE_USER="${LOGROTATE_USER:-$(systemctl show -p User --value "$SERVICE" 2>/dev/null || true)}"
LOGROTATE_GROUP="${LOGROTATE_GROUP:-${LOGROTATE_USER:-$(systemctl show -p Group --value "$SERVICE" 2>/dev/null || true)}}"
SU_LINE=""
if [ -n "$LOGROTATE_USER" ] && [ "$LOGROTATE_USER" != "root" ]; then
  SU_LINE="    su ${LOGROTATE_USER} ${LOGROTATE_GROUP:-$LOGROTATE_USER}"
fi

{
  echo "# ${SERVICE} daily log rotation (generated by $(basename "$0")), keep 5 archives"
  printf '%s {\n' "$LOG_FILES"
  echo "    daily"
  echo "    rotate 5"
  echo "    dateext"
  echo "    compress"
  echo "    delaycompress"
  echo "    copytruncate"
  echo "    missingok"
  echo "    notifempty"
  [ -n "$SU_LINE" ] && echo "$SU_LINE"
  echo "}"
} > "$DEST"

echo "[logrotate] wrote ${DEST}"
echo "  log files :${LOG_FILES}"
echo "  rule      : daily, keep last 5, compress archives"
if [ -n "$SU_LINE" ]; then
  echo "  as user   : ${LOGROTATE_USER}:${LOGROTATE_GROUP:-$LOGROTATE_USER} (owner of the log dir)"
else
  echo "  as user   : (not set - log dir is expected to be root-owned)"
fi
echo
echo "Dry run (no rotation):    logrotate -d ${DEST}"
echo "Rotate now:               logrotate -f ${DEST}"
echo "Daily job enabled?        ls -l /etc/cron.daily/logrotate  |  systemctl list-timers | grep logrotate"
